name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      # Ensure gh-pages exists (prevents first-deploy git 128)
      - name: Ensure gh-pages exists
        run: |
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            git config user.email "automation@example.com"
            git config user.name "Automation bot"
            git checkout --orphan gh-pages
            git rm -rf .
            git commit --allow-empty -m "initialize gh-pages"
            git push origin gh-pages
            git checkout -
          fi

      # Detect branch and expose *outputs* used later
      - id: branch-name
        name: Detect branch info
        run: |
          ref="${GITHUB_REF##*/}"
          echo "current_branch=$ref" >> "$GITHUB_OUTPUT"
          if [ "$ref" = "${{ github.event.repository.default_branch }}" ]; then
            echo "is_default=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_default=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Update the image to latest publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o ./input-cache/publisher.jar --create-dirs

      - name: Create package cache folder
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          entrypoint: /bin/sh
          args: -c "mkdir -p ./fhir-package-cache && chown 1001:127 ./fhir-package-cache"

      - name: Run the IG publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: java -Xmx4g -jar ./input-cache/publisher.jar publisher -ig . -auto-ig-build -repo https://github.com/${{ github.repository }} -package-cache-folder ./fhir-package-cache

      - name: List output directory contents
        run: ls -la ./output

      - name: Deploy candidate
        if: ${{ steps.branch-name.outputs.is_default == 'false' }}
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          branch: gh-pages
          folder: ./output
          commit-message: Deploy candidate branch
          target-folder: branches/${{ steps.branch-name.outputs.current_branch }}
          single-commit: true
          clean: false
          clean-exclude: branches

      - name: Deploy main
        if: ${{ steps.branch-name.outputs.is_default == 'true' }}
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          branch: gh-pages
          folder: ./output
          commit-message: Deploy main branch
          single-commit: true
          clean-exclude: branches
